pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Automatic merge from dependabot
    conditions:
      - "author=dependabot"
    actions:
      merge:
        method: merge